---
cluster_nodes:
  - name: mega-sno
    type: sno
    infra:
      name: labEndurance
      # type: vsphere | nutanix | libvirt | baremetal
      type: libvirt
    vm:
      cpu_cores: 64
      cpu_sockets: 2
      cpu_threads: 1
      memory: 491520
      disks:
        - size: 320
          name: boot
        - size: 2400
          name: data
    pci_devices:
      # c1:00.0 VGA compatible controller: NVIDIA Corporation GA104GL [RTX A4000] (rev a1)
      # c1:00.1 Audio device: NVIDIA Corporation GA104 High Definition Audio Controller (rev a1)
      - "c1:00.0"
      - "c1:00.1"
      # PCIe USB 3.1 Card - Has Coral Edge TPU
      # 2a:00.0 USB controller: ASMedia Technology Inc. ASM2142 USB 3.1 Host Controller
      # 2f:00.0 USB controller: ASMedia Technology Inc. ASM2142 USB 3.1 Host Controller
      #- "2a:00.0"
      #- "2f:00.0"
      # 61:00.0 Ethernet controller: Mellanox Technologies MT42822 BlueField-2 integrated ConnectX-6 Dx network controller (rev 01)
      # 61:00.1 Ethernet controller: Mellanox Technologies MT42822 BlueField-2 integrated ConnectX-6 Dx network controller (rev 01)
      # 61:00.2 DMA controller: Mellanox Technologies MT42822 BlueField-2 SoC Management Interface (rev 01)
      # - "61:00.0"
      # - "61:00.1"
      # - "61:00.2"
    networking:
      interfaces:
        - name: eth0
          mac_address: 54:52:00:49:60:70
          dhcp: false
          ipv4:
            - address: 192.168.60.70
              prefix: 23
      routes:
        - destination: 0.0.0.0/0
          next_hop_address: 192.168.60.1
          next_hop_interface: eth0
          table_id: 254
