---
- name: Set facts for an empty list
  ansible.builtin.set_fact:
    target_sources: []

- name: Add set NTP Sources just by the address
  ansible.builtin.set_fact:
    target_sources: "{{ target_sources + [source.address] }}"
  loop: "{{ ntp_sources }}"
  loop_control:
    loop_var: source

- name: Combine no proxy list
  ansible.builtin.set_fact:
    cluster_ntp_sources: "{{ target_sources | join(',') }}"

- name: Set body data
  ansible.builtin.set_fact:
    override_ntp_ic_body_cluster: "{ \"additional_ntp_source\": \"{{ cluster_ntp_sources | default('0.pool.ntp.org') }}\" }"
    override_ntp_ic_body_infraenv: "{ \"additional_ntp_sources\": \"{{ cluster_ntp_sources | default('0.pool.ntp.org') }}\" }"

- name: Inject NTP config into the Cluster
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
    return_content: true
    method: PATCH
    body: '{{ override_ntp_ic_body_cluster }}'
    status_code: 201
    body_format: json
  register: ntp_cluster_resp
  retries: 5
  delay: 30
  until: ntp_cluster_resp.status == 201

- name: Inject NTP config into the InfraEnv
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: true
    method: PATCH
    body: '{{ override_ntp_ic_body_infraenv }}'
    status_code: 201
    body_format: json
  register: ntp_infraenv_resp
  retries: 5
  delay: 30
  until: ntp_infraenv_resp.status == 201
