---
- name: Template out ISO Parameters
  ansible.builtin.template:
    src: templates/iso_params.json.j2
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/iso_params.json"
    mode: '0644'

- name: AI Svc - Post ISO Parameters
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: true
    method: PATCH
    body: "{{ lookup('ansible.builtin.template', 'templates/iso_params.json.j2') }}"
    status_code: 201
    body_format: json
  register: set_cluster_iso_params
  retries: 5
  delay: 30
  until: set_cluster_iso_params.status == 201
