---

- name: Template out the deployment.json file
  ansible.builtin.template:
    src: templates/deployment.json.j2
    dest: "{{ generated_asset_directory }}/deployment-{{ deployment_name }}.json"
    mode: '0644'

- name: AI Service - Create Cluster
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/"
    return_content: true
    method: POST
    body: "{{ lookup('ansible.builtin.template', 'templates/deployment.json.j2') }}"
    status_code: 201
    body_format: json
  register: create_cluster
  retries: 5
  delay: 30
  until: create_cluster.status == 201

- name: Set facts for Cluster
  when: (create_cluster.json.base_dns_domain == cluster_domain) and (create_cluster.json.name == cluster_name)
  ansible.builtin.set_fact:
    cluster_id: "{{ create_cluster.json.id }}"
    cluster_status: "{{ create_cluster.json.status }}"
