---
- name: Template out the infraenv.json file
  ansible.builtin.template:
    src: templates/infraenv.json.j2
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/infraenv.json"
    mode: '0644'

- name: AI Service - Create Infraenv
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/"
    return_content: true
    method: POST
    body: "{{ lookup('ansible.builtin.template', 'templates/infraenv.json.j2') }}"
    status_code: 201
    body_format: json
  register: create_infraenv
  retries: 5
  delay: 30
  until: create_infraenv.status == 201

- name: Set facts for Infraenv
  when: (create_infraenv.json.cluster_id == cluster_id) and (create_infraenv.json.name == cluster_name)
  ansible.builtin.set_fact:
    infraenv_id: "{{ create_infraenv.json.id }}"
    infraenv_download_url: "{{ create_infraenv.json.download_url }}"
