---
- name: Ensure the cluster is in a valid state to get ready to install...
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
    return_content: true
    method: GET
    status_code: 200
    body_format: json
  register: cluster_current_status
  until: cluster_current_status.json is defined
  retries: 5
  delay: 30

- name: Start the Installation of the OpenShift Cluster
  when: cluster_current_status.json.status == "ready"
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/install"
    return_content: true
    method: POST
    status_code: 202
    body_format: json
